version: 2

models:
  - name: stg_customer
    columns:
      - name: customer_id
        tests:
          - not_null

  - name: stg_order
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: order_status
        tests:
          - accepted_values:
              values:
                [
                  'delivered',
                  'shipped'
                ]